# require: rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'examples/**'

# BEGIN
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
# END
